apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-smtp-external
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend-cluster
    kind: ClusterSecretStore
  target:
    name: alertmanager-smtp-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        values.yaml: |
          alertmanager:
            config:
              global:
                smtp_auth_password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: taskmanager/app
        property: email_app_password
