apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - prometheus-deployment.yaml
  - grafana-deployment.yaml
  - configmaps.yaml
  - alertmanager-secret.yaml
  - loki-values.yaml
  - loki-deployment.yaml
  - dashboards/taskmanager-metrics.yaml
  - dashboards/jenkins-cicd-metrics.yaml
