apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-values
  namespace: monitoring
data:
  values.yaml: |
    loki:
      enabled: true
      persistence:
        enabled: false
      podAnnotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3100"
        prometheus.io/path: "/metrics"
      config:
        table_manager:
          retention_deletes_enabled: true
          retention_period: 168h
    promtail:
      enabled: true
      config:
        snippets:
          extraScrapeConfigs: ""
    grafana:
      enabled: false
    prometheus:
      enabled: false
