apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backend-secrets-external
  namespace: taskmanager
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: backend-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: taskmanager
        property: DB_PASSWORD
    - secretKey: JWT_SECRET
      remoteRef:
        key: taskmanager
        property: JWT_SECRET
    - secretKey: GOOGLE_CLIENT_ID
      remoteRef:
        key: taskmanager
        property: GOOGLE_CLIENT_ID
    - secretKey: GOOGLE_CLIENT_SECRET
      remoteRef:
        key: taskmanager
        property: GOOGLE_CLIENT_SECRET
