apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backend-secrets-external
  namespace: taskmanager
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: backend-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: taskmanager/db
        property: password
    - secretKey: JWT_SECRET
      remoteRef:
        key: taskmanager/app
        property: jwt_secret
    - secretKey: GOOGLE_CLIENT_ID
      remoteRef:
        key: taskmanager/google
        property: client_id
    - secretKey: GOOGLE_CLIENT_SECRET
      remoteRef:
        key: taskmanager/google
        property: client_secret
    - secretKey: EMAIL_USER
      remoteRef:
        key: taskmanager/app
        property: email_user
    - secretKey: EMAIL_APP_PASSWORD
      remoteRef:
        key: taskmanager/app
        property: email_app_password
    - secretKey: ALERT_EMAIL_TO
      remoteRef:
        key: taskmanager/app
        property: alert_email_to
    - secretKey: REPLICATION_PASSWORD
      remoteRef:
        key: taskmanager/app
        property: replication_password
