apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: taskmanager
resources:
  - configmap.yaml
  - services.yaml
  - postgres-statefulset.yaml
  - deployment-advanced.yaml
  - hpa-advanced.yaml
  - pdb-advanced.yaml
  - ingress.yaml
  - network-policies.yaml
  - externalsecret.yaml
  - secretstore.yaml
  - pvc.yaml
