apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - postgres-deployment.yaml
  - configmap.yaml
  - external-secret.yaml
  - vault-secretstore.yaml
  - ingress.yaml
  - networkpolicies/backend-netpol.yaml
  - networkpolicies/postgres-netpol.yaml
  - hpa/backend-hpa.yaml
  - hpa/frontend-hpa.yaml
  - pdb/backend-pdb.yaml
  - pdb/frontend-pdb.yaml
