apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: taskmanager
resources:
  - backend-service.yaml
  - frontend-service.yaml
  - postgres-cluster.yaml
  - deployment-advanced.yaml
  - hpa-advanced.yaml
  - ingress.yaml
  - external-secret.yaml
  - vault-secretstore.yaml
  - vault-clustersecretstore.yaml
