apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend-pdb
  namespace: taskmanager
  labels:
    app: backend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: backend
  unhealthyPodEvictionPolicy: AlwaysAllow
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend-pdb
  namespace: taskmanager
  labels:
    app: frontend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: frontend
  unhealthyPodEvictionPolicy: AlwaysAllow
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: postgres-pdb
  namespace: taskmanager
  labels:
    app: postgres
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: postgres
  unhealthyPodEvictionPolicy: AlwaysAllow
