apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: taskmanager-db
  namespace: taskmanager
spec:
  instances: 2
  livenessProbeTimeout: 60
  inheritedMetadata:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9187"
      prometheus.io/path: "/metrics"
  enableSuperuserAccess: true
  superuserSecret:
    name: postgres-superuser-secret
  bootstrap:
    initdb:
      database: taskmanager
      owner: postgres
  storage:
    size: 1Gi
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
